[meta]
moe = "mon3tr_(arknights)"
use = "mocha"

[colors]
rosewater  = "#f5e5e0"
flamingo   = "#f2c9c0"
pink       = "#ffb0c9"
mauve      = "#b8a4ff"
red        = "#ff442e"
maroon     = "#b03a33"
peach      = "#f7bd8f"
yellow     = "#fcd912"
green      = "#5ad641"
teal       = "#5fb8a8"
sky        = "#96d8d0"
sapphire   = "#4d9fd0"
blue       = "#3c8dd9"
lavender   = "#a1c1ff"
text       = "#e8e1cf"
subtext1   = "#dacfb3"
subtext0   = "#cdbe97"
overlay2   = "#92a89a"
overlay1   = "#7b9685"
overlay0   = "#678171"
surface2   = "#556b5d"
surface1   = "#435449"
surface0   = "#313d35"
base       = "#1f2722"
mantle     = "#181e1a"
crust      = "#111513"

[colors.ansi]
black         = "#435449"
bright_black  = "#54695c"
red           = "#ff442e"
bright_red    = "#ff300f"
green         = "#5ad641"
bright_green  = "#41cc2c"
yellow        = "#fcd912"
bright_yellow = "#ecd103"
blue          = "#3c8dd9"
bright_blue   = "#2878ce"
magenta       = "#ffb0c9"
bright_magenta= "#ff91b0"
cyan          = "#5fb8a8"
bright_cyan   = "#4cac9e"
white         = "#cdbe97"
bright_white  = "#d9cfb1"
