[meta]
moe = "kal'tsit_(arknights)"
use = "latte"

[colors]
rosewater  = "#b58f8f"
flamingo   = "#c28483"
pink       = "#c180a9"
mauve      = "#aa84da"
red        = "#d35b5b"
maroon     = "#b24444"
peach      = "#c38e66"
yellow     = "#9c9e2f"
green      = "#77a05e"
teal       = "#4aa99e"
sky        = "#5d9db8"
sapphire   = "#359fbd"
blue       = "#4f83e3"
lavender   = "#8d91e5"
text       = "#4c4b50"
subtext1   = "#5c5b5e"
subtext0   = "#6c6b6c"
overlay2   = "#828283"
overlay1   = "#929291"
overlay0   = "#a2a3a0"
surface2   = "#b2b3ae"
surface1   = "#c2c3bc"
surface0   = "#d2d3ca"
base       = "#f5f4e5"
mantle     = "#ececdf"
crust      = "#e2e3d8"

[colors.ansi]
black         = "#5c5b5e"
bright_black  = "#6b6a6d"
red           = "#d35b5b"
bright_red    = "#db7c78"
green         = "#77a05e"
bright_green  = "#89ae75"
yellow        = "#9c9e2f"
bright_yellow = "#b4bb38"
blue          = "#4f83e3"
bright_blue   = "#6f96e8"
magenta       = "#c180a9"
bright_magenta= "#cd99b8"
cyan          = "#4aa99e"
bright_cyan   = "#5fb9b2"
white         = "#b2b3ae"
bright_white  = "#c1c2be"
