[meta]
moe = "theresa_(arknights)"
use = "latte"

[colors]
rosewater  = "#cf6d7d"
flamingo   = "#dd6363"
pink       = "#b74757"
mauve      = "#af78af"
red        = "#d7425b"
maroon     = "#8a4254"
peach      = "#ca7623"
yellow     = "#a7851d"
green      = "#4b9b66"
teal       = "#419891"
sky        = "#4692b8"
sapphire   = "#5d8fc1"
blue       = "#597bc0"
lavender   = "#8d82c3"
text       = "#534853"
subtext1   = "#635663"
subtext0   = "#746474"
overlay2   = "#985a56"
overlay1   = "#a86965"
overlay0   = "#b37c78"
surface2   = "#be8f8c"
surface1   = "#c9a29f"
surface0   = "#d4b5b3"
base       = "#eadbda"
mantle     = "#e4d2d0"
crust      = "#dfc8c6"

[colors.ansi]
black         = "#635663"
bright_black  = "#736473"
red           = "#d7425b"
bright_red    = "#de6172"
green         = "#4b9b66"
bright_green  = "#5bb07b"
yellow        = "#a7851d"
bright_yellow = "#c7a423"
blue          = "#597bc0"
bright_blue   = "#748eca"
magenta       = "#b74757"
bright_magenta= "#c2616c"
cyan          = "#419891"
bright_cyan   = "#4cb2ad"
white         = "#be8f8c"
bright_white  = "#c9a39f"
