[meta]
moe = "priestess_(arknights)"
use = "macchiato"

[colors]
rosewater  = "#efddda"
flamingo   = "#e9cccc"
pink       = "#af9fce"
mauve      = "#d5b3f8"
red        = "#dd96a0"
maroon     = "#e1a5aa"
peach      = "#e3ae90"
yellow     = "#e2cfaa"
green      = "#abcf9f"
teal       = "#96c9c2"
sky        = "#9dced6"
sapphire   = "#8cbed4"
blue       = "#99b2e4"
lavender   = "#c0c4ee"
text       = "#dad7d9"
subtext1   = "#c6c1c4"
subtext0   = "#b2acb0"
overlay2   = "#97749e"
overlay1   = "#82608a"
overlay0   = "#6c5072"
surface2   = "#553f5a"
surface1   = "#413045"
surface0   = "#2a1f2d"
base       = "#140f15"
mantle     = "#0b080c"
crust      = "#030203"

[colors.ansi]
black         = "#413045"
bright_black  = "#57405c"
red           = "#dd96a0"
bright_red    = "#d57e88"
green         = "#abcf9f"
bright_green  = "#97c58a"
yellow        = "#e2cfaa"
bright_yellow = "#dac493"
blue          = "#99b2e4"
bright_blue   = "#809cdd"
magenta       = "#af9fce"
bright_magenta= "#a08ac3"
cyan          = "#96c9c2"
bright_cyan   = "#81beb8"
white         = "#b2acb0"
bright_white  = "#c4c0c3"
