[meta]
moe = "amiya_(medic)_(solo_around_the_world)_(arknights)"
use = "mocha"

[colors]
rosewater  = "#f2d5cf"
flamingo   = "#dcafa6"
pink       = "#e5b8c3"
mauve      = "#7363aa"
red        = "#d78579"
maroon     = "#a06e5c"
peach      = "#e5b484"
yellow     = "#e5c76b"
green      = "#88b39a"
teal       = "#88c1b7"
sky        = "#a6c2d6"
sapphire   = "#5583c1"
blue       = "#84a0c6"
lavender   = "#8d9ad5"
text       = "#fbfaf9"
subtext1   = "#e9e3dc"
subtext0   = "#daccbf"
overlay2   = "#8d8db9"
overlay1   = "#7070a7"
overlay0   = "#5a5a94"
surface2   = "#4b4b7b"
surface1   = "#3b3b62"
surface0   = "#2c2c48"
base       = "#212136"
mantle     = "#171725"
crust      = "#11111c"

[colors.ansi]
black         = "#3b3b62"
bright_black  = "#4b497a"
red           = "#d78579"
bright_red    = "#d07361"
green         = "#88b39a"
bright_green  = "#75a78c"
yellow        = "#e5c76b"
bright_yellow = "#e0c251"
blue          = "#84a0c6"
bright_blue   = "#6f8dbc"
magenta       = "#e5b8c3"
bright_magenta= "#dda1ae"
cyan          = "#88c1b7"
bright_cyan   = "#74b6ad"
white         = "#d5a79f"
bright_white  = "#e1c1ba"
