[meta]
moe = "shamare_(arknights)"
use = "frapp√©"

[colors]
rosewater  = "#f2ced5"
flamingo   = "#efb9c3"
pink       = "#e8a2c0"
mauve      = "#dda6e3"
red        = "#e591a2"
maroon     = "#b97c88"
peach      = "#e8b49a"
yellow     = "#f0d591"
green      = "#a9d8b8"
teal       = "#9acecf"
sky        = "#b3cbf2"
sapphire   = "#8793c2"
blue       = "#a6b3e3"
lavender   = "#b8a9c3"
text       = "#e2dcec"
subtext1   = "#cfc5dd"
subtext0   = "#bcb3c9"
overlay2   = "#a89fbd"
overlay1   = "#9288a8"
overlay0   = "#817896"
surface2   = "#6c647d"
surface1   = "#5b536c"
surface0   = "#4a435a"
base       = "#3a314a"
mantle     = "#322b41"
crust      = "#2a2436"

[colors.ansi]
black         = "#5b536c"
bright_black  = "#6e6482"
red           = "#e591a2"
bright_red    = "#df7889"
green         = "#a9d8b8"
bright_green  = "#94cea8"
yellow        = "#f0d591"
bright_yellow = "#eccf76"
blue          = "#a6b3e3"
bright_blue   = "#8e9cdc"
magenta       = "#e8a2c0"
bright_magenta= "#e289ac"
cyan          = "#9acecf"
bright_cyan   = "#85c2c5"
white         = "#bcb3c9"
bright_white  = "#d0c9d9"
