[meta]
moe = "myrtle_(bustling_festival)_(arknights)"
use = "latte"

[colors]
rosewater  = "#d0755b"
flamingo   = "#f15c5c"
pink       = "#ca757d"
mauve      = "#b85ea1"
red        = "#e75454"
maroon     = "#be4f48"
peach      = "#fe4f06"
yellow     = "#bf8037"
green      = "#329f6b"
teal       = "#4f9a91"
sky        = "#7991a7"
sapphire   = "#356593"
blue       = "#497fb2"
lavender   = "#a97ebc"
text       = "#5a4540"
subtext1   = "#6b524c"
subtext0   = "#7a5d56"
overlay2   = "#558d80"
overlay1   = "#619f91"
overlay0   = "#74ab9e"
surface2   = "#87b6ab"
surface1   = "#9ac2b9"
surface0   = "#adcdc6"
base       = "#d3e5e1"
mantle     = "#cadfda"
crust      = "#c0d9d3"

[colors.ansi]
black         = "#6b524c"
bright_black  = "#7d6158"
red           = "#e75454"
bright_red    = "#ec7975"
green         = "#329f6b"
bright_green  = "#3bbb82"
yellow        = "#bf8037"
bright_yellow = "#cc964f"
blue          = "#497fb2"
bright_blue   = "#628ebf"
magenta       = "#ca757d"
bright_magenta= "#d49094"
cyan          = "#4f9a91"
bright_cyan   = "#61aea7"
white         = "#87b6ab"
bright_white  = "#9ac1b9"
