[meta]
moe = "suzuran_(arknights)"
use = "latte"

[colors]
rosewater  = "#8f4e4c"
flamingo   = "#874542"
pink       = "#8e4561"
mauve      = "#6b4a7f"
red        = "#b43842"
maroon     = "#a34246"
peach      = "#8f5524"
yellow     = "#6e5715"
green      = "#0c6b51"
teal       = "#18685a"
sky        = "#255b74"
sapphire   = "#066ca2"
blue       = "#386a8f"
lavender   = "#715894"
text       = "#111115"
subtext1   = "#1e1f24"
subtext0   = "#2b2e34"
overlay2   = "#6c5a0d"
overlay1   = "#806b12"
overlay0   = "#947c16"
surface2   = "#a48f3f"
surface1   = "#b5a25e"
surface0   = "#c5b57b"
base       = "#e7dcb4"
mantle     = "#ded2a6"
crust      = "#d6c897"

[colors.ansi]
black         = "#1e1f24"
bright_black  = "#2c2d34"
red           = "#b43842"
bright_red    = "#c74a50"
green         = "#0c6b51"
bright_green  = "#108c6e"
yellow        = "#6e5715"
bright_yellow = "#8d741b"
blue          = "#386a8f"
bright_blue   = "#427aaa"
magenta       = "#8e4561"
bright_magenta= "#a7516f"
cyan          = "#18685a"
bright_cyan   = "#1f8678"
white         = "#a48f3f"
bright_white  = "#b9a548"
