[meta]
moe = "spot_(arknights)"
use = "latte"

[colors]
rosewater  = "#b63b7f"
flamingo   = "#d02244"
pink       = "#cc3377"
mauve      = "#4a2a6b"
red        = "#cc3333"
maroon     = "#7a1f1f"
peach      = "#b85e05"
yellow     = "#947400"
green      = "#528439"
teal       = "#1937e1"
sky        = "#0c74e4"
sapphire   = "#0073be"
blue       = "#004c7a"
lavender   = "#8f63bb"
text       = "#222222"
subtext1   = "#121212"
subtext0   = "#1a1a1a"
overlay2   = "#595959"
overlay1   = "#696969"
overlay0   = "#787878"
surface2   = "#878787"
surface1   = "#969696"
surface0   = "#a6a6a6"
base       = "#c4c4c4"
mantle     = "#bdbdbd"
crust      = "#b5b5b5"

[colors.ansi]
black         = "#121212"
bright_black  = "#212121"
red           = "#cc3333"
bright_red    = "#d35551"
green         = "#528439"
bright_green  = "#5f9e44"
yellow        = "#947400"
bright_yellow = "#b99700"
blue          = "#004c7a"
bright_blue   = "#005e9f"
magenta       = "#cc3377"
bright_magenta= "#d35187"
cyan          = "#1937e1"
bright_cyan   = "#374be9"
white         = "#878787"
bright_white  = "#969696"
