[meta]
moe = "rosmontis_(arknights)"
use = "latte"

[colors]
rosewater  = "#cf6d4f"
flamingo   = "#d27051"
pink       = "#b87f53"
mauve      = "#6c699f"
red        = "#dc634d"
maroon     = "#b04f4a"
peach      = "#d1732f"
yellow     = "#b3821f"
green      = "#469b60"
teal       = "#5a9591"
sky        = "#7d8da2"
sapphire   = "#4c6c94"
blue       = "#5e81ac"
lavender   = "#7c79a9"
text       = "#3b4251"
subtext1   = "#4a5161"
subtext0   = "#5a616f"
overlay2   = "#636986"
overlay1   = "#727896"
overlay0   = "#838aa4"
surface2   = "#939bb2"
surface1   = "#a4abc1"
surface0   = "#b5bcce"
base       = "#d8dee8"
mantle     = "#ced5e3"
crust      = "#c5cddd"

[colors.ansi]
black         = "#4a5161"
bright_black  = "#575e72"
red           = "#dc634d"
bright_red    = "#e2826c"
green         = "#469b60"
bright_green  = "#54b274"
yellow        = "#b3821f"
bright_yellow = "#d39f24"
blue          = "#5e81ac"
bright_blue   = "#7792b9"
magenta       = "#b87f53"
bright_magenta= "#c3956d"
cyan          = "#5a9591"
bright_cyan   = "#6da7a5"
white         = "#939bb2"
bright_white  = "#a5aabf"
