[meta]
moe = "nozomi_(blue_archive)"
use = "frapp√©"

[colors]
rosewater  = "#f5e0dc"
flamingo   = "#f2cdcd"
pink       = "#f5c2e7"
mauve      = "#cba6f7"
red        = "#f38ba8"
maroon     = "#eba0ac"
peach      = "#fab387"
yellow     = "#f9e2af"
green      = "#a6e3a1"
teal       = "#94e2d5"
sky        = "#89dceb"
sapphire   = "#74c7ec"
blue       = "#89b4fa"
lavender   = "#b4befe"
text       = "#f4f9e3"
subtext1   = "#e0e6d0"
subtext0   = "#ccd2bd"
overlay2   = "#9ea0b6"
overlay1   = "#8c8da3"
overlay0   = "#7a7b91"
surface2   = "#686a7f"
surface1   = "#58596d"
surface0   = "#47495c"
base       = "#292a3c"
mantle     = "#303143"
crust      = "#38394c"

[colors.ansi]
black         = "#58596d"
bright_black  = "#696982"
red           = "#f38ba8"
bright_red    = "#f06f8f"
green         = "#a6e3a1"
bright_green  = "#8ddc89"
yellow        = "#f9e2af"
bright_yellow = "#f7db92"
blue          = "#89b4fa"
bright_blue   = "#6b9cf9"
magenta       = "#f5c2e7"
bright_magenta= "#f1a7da"
cyan          = "#94e2d5"
bright_cyan   = "#7cdbcf"
white         = "#ccd2bd"
bright_white  = "#dde2d4"
