[meta]
moe = "sussurro_(travel_freely)_(arknights)"
use = "macchiato"

[colors]
rosewater  = "#f0dadb"
flamingo   = "#edb4b8"
pink       = "#e5b4c4"
mauve      = "#7462aa"
red        = "#c94049"
maroon     = "#ad3139"
peach      = "#de9657"
yellow     = "#dbd756"
green      = "#84bc8c"
teal       = "#9dc6b9"
sky        = "#cadde7"
sapphire   = "#649fbf"
blue       = "#7fadc5"
lavender   = "#a9b0d4"
text       = "#ece0d8"
subtext1   = "#d1cecb"
subtext0   = "#bababa"
overlay2   = "#98969c"
overlay1   = "#858585"
overlay0   = "#717171"
surface2   = "#5c5c5c"
surface1   = "#4a4a4a"
surface0   = "#353537"
base       = "#202024"
mantle     = "#19181b"
crust      = "#121113"

[colors.ansi]
black         = "#4a4a4a"
bright_black  = "#5d5d5d"
red           = "#c94049"
bright_red    = "#b63438"
green         = "#84bc8c"
bright_green  = "#70b17b"
yellow        = "#dbd756"
bright_yellow = "#d5d63c"
blue          = "#7fadc5"
bright_blue   = "#6a9dbb"
magenta       = "#e5b4c4"
bright_magenta= "#dd9db0"
cyan          = "#9dc6b9"
bright_cyan   = "#89bbad"
white         = "#bababa"
bright_white  = "#cdcdcd"
